version: "1.0"
services:
  frontend:
    image: paperless:nginx
    build:
      dockerfile: ui/Dockerfile
    ports:
      - "8080:80"
  backend:
    image: paperless:openjdk
    build:
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
  postgres:
    image: postgres:latest
    container_name: paperless-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=paperless
      - POSTGRES_PASSWORD=paperless
      - POSTGRES_DB=paperless
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./Paperless_DM.sql:/docker-entrypoint-initdb.d/PaperLess_DM.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "paperless" ]
      interval: 10s
      timeout: 5s
      retries: 20